### ISSUE TITLE
game crash always at the same time

### ISSUE THREAD

**Issue by 4lex1615141819** [flathub/io.github.lime3ds.Lime3DS#16]
### Lime3DS Version

cinnamon cinnamon (x11)

### Description

It always crashes at the same time, although i'm not doing anything that hasn't been done in the game before

### Reproduction Certainty

Always

### Logs and Backtraces

[lime3ds_log.txt](https://github.com/flathub/io.github.lime3ds.Lime3DS/files/15293190/lime3ds_log.txt)

**Comment by OpenSauce04** [comment]
This issue lacks important information. Please fill out all fields, including what game you were playing and what you were doing to cause the issue
Additionally, try replicating the issue with the AppImage. If you can replicate the issue with the AppImage, create an issue on the main Lime3DS repo
