### ISSUE TITLE
Crashes when I click anything

### ISSUE THREAD

**Issue by LikkleS** [flathub/io.github.lime3ds.Lime3DS#31]
### Lime3DS Version

2117

### Description

I cant do anything without it crashing

### Reproduction Certainty

Always

**Comment by OpenSauce04** [comment]
Please fill out the issue form correctly.

**Comment by powerpuffboysz** [comment]
i was having a similar issue until i told lime3ds to open lime3ds folder and found for whatever reason it was opening the "user" file in my home directory for shadps4. if that folder exists try moving or renaming it it might start working again
